---
- name: install premise package
  apt:
    name:
      - ca-certificates
      - curl
      - apt-transport-https
      - lsb-release
      - gnupg
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: import MS repository key
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: import MS repository
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main
    state: present

- name: install azure-cli
  apt:
    name: azure-cli
    state: present

- name: pip install packageing
  pip:
    name:
      - packaging
      - msrestazure
      - ansible[azure]
