---
- name: Add Apt key for postgres repo
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Install postgres repo
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    state: present

- name: install psql client package
  apt:
    name:
      - postgresql-client-11
    update_cache: yes
    cache_valid_time: 3600
    state: present
