---
- name: Install pre docker package
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Add Apt key for docker repo
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install docker-ce
  apt:
    name: docker-ce=5:19.03.9~3-0~ubuntu-bionic
  notify: restart docker

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: +x
  become: yes
